name: formulas
channels:
  - conda-forge
  - defaults
dependencies:
  - docutils
  - flask
  - jupyterlab >=0.35.5,<0.36
  - multiprocess
  - numpy >=1.15
  - openpyxl
  - pip
  - python >=3.7,<3.8.0a0
  - python-graphviz
  - regex
  - tornado<6
  - pip:
    - schedula >=1.1.1
