
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T10:59:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "067eddde7a3125ca917afcffd1469cd15233f3a9",
 "version": "2021.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
