
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-11T17:47:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "523f0a3772cb4bad664f1dad67a46f5b86c3d629",
 "version": "2.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
