[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ['py38']
include = 'vula/\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.venv
  | _build
  | build
  | dist
)/
'''
