
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-18T11:58:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e45d96656f26a197dd965cafc44f34ff621a5876",
 "version": "1.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
