
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T13:42:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "71d7e451d9cbd7abe2850c9f904e4bf5cb028107",
 "version": "1.15.0.post.dev290"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
