
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "branch": "1.6.1)",
 "date": "2021-10-11T18:04:44+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "47e7c50d34e87c0e17d5380ce8892439fdf2afc6",
 "repository": "https://github.com/metawards/MetaWards",
 "version": "1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
