db2set DB2_OBJECT_STORAGE_LOCAL_STAGING_PATH={{ db2_s3_staging_path }}
db2set DB2_OBJECT_STORAGE_SETTINGS=ON:DownloadConcurrency=4
#db2set DB2AUTH=OSAUTHDB,ALLOW_LOCAL_FALLBACK,PLUGIN_AUTO_RELOAD
db2set B2_OBJECT_TABLE_ENTRIES=65532
db2set DB2_LOAD_COPY_NO_OVERRIDE="COPY YES TO DB2REMOTE://{{ db2_s3_loadalias_name }}//CSYS.{{ id }}//LoadCopies"
db2set DB2ENVLIST=GSK_STRICTCHECK_CBCPADBYTES
db2set DB2_VERIFY_PAGE_AFTER_IO=TRUE
db2set DB2_ENABLE_HADR_LOG_PAGE_INTEGRITY_CHECK=3
db2set DB2_REMSTG_SERVER_DEFAULT={{ cos_endpoint }}
db2set DB2FODC=DUMPSHM=ON CORESHM=OFF
db2set DB2_ATS_ENABLE=1
db2set DB2_AUTOSTART=OFF
db2set DB2COMM=TCPIP,SSL

# set only on standby?
db2set DB2_HADR_ROS=YES
db2set DB2_STANDBY_ISO=UR


