[tool.poetry]
name = "miningpoolhub_py"
version = "0.1.5"
description = "A Python wrapper for the Mining Pool Hub REST API"
authors = ["CoryKrol <16892390+CoryKrol@users.noreply.github.com>"]
license = "Apache 2"
readme = "README.md"
homepage = "https://github.com/CoryKrol/miningpoolhub_py"
repository = "https://github.com/CoryKrol/miningpoolhub_py"

include = [
    "LICENSE.md",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
python-dotenv = "^0.19.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
vcrpy = "^4.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
