# Fake terraform for hard coded metal

# Metal topology is in JSON
# [
#   {
#       "name": "sf-1",
#       "egress_ip": "{{hostvars['sf1']['egress_ip']}}",
#       "egress_nic": "eth0",
#       "mesh_ip": "{{hostvars['sf1']['mesh_ip']}}",
#       "mesh_nic": "eth1"
#   },
# ...
# ]

- name: Log metal topology
  debug:
    msg: "{{topology}}"

- name: Add metal nodes
  # This include is to work around the lack of blocks in loops
  include: terraform_add_node.yml
  loop: "{{topology}}"
