
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-17T13:05:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "676e18c22abe398b524e2fd6da316b4e97936b8d",
 "version": "1.0.4a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
