[tool.poetry]
name = "psql2bigquery"
version = "0.0.1"
description = "Export PostgreSQL databases to Google Cloud Platform BigQuery"
authors = ["Joao Daher <joao@daher.dev>"]
repository = "https://github.com/CraveFood/psql2bigquery"
readme = "README.md"
keywords = ["postgresql", "bigquery", "sink"]
packages = [
    { include = "psql2bigquery" },
]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
click = "*"
google-cloud-bigquery = "*"
psycopg2-binary = "*"
sentry-sdk = {version = "*", optional = true}

[tool.poetry.extras]
sentry = ["sentry-sdk"]

[tool.poetry.dev-dependencies]
black = "*"
pylint = "*"

[tool.poetry.scripts]
psql2bigquery = 'psql2bigquery.main:cli'

[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"
