[tool.poetry]
name = "levo-ssrfmap"
version = "0.1.0"
description = "A packaged version of the SSRFmap CLI tool."
authors = ["Akshath Kothari <akshath.kothari@levo.ai>"]
packages = [
    {include = "ssrfmap", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"

[tool.poetry.scripts]
ssrfmap = "ssrfmap.cli:ssrfmap"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
