# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ortools/constraint_solver/search_stats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ortools/constraint_solver/search_stats.proto',
  package='operations_research',
  syntax='proto3',
  serialized_options=b'\n#com.google.ortools.constraintsolverP\001\252\002\037Google.OrTools.ConstraintSolver',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,ortools/constraint_solver/search_stats.proto\x12\x13operations_research\"\x94\x05\n\x15LocalSearchStatistics\x12r\n local_search_operator_statistics\x18\x01 \x03(\x0b\x32H.operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics\x12n\n\x1elocal_search_filter_statistics\x18\x02 \x03(\x0b\x32\x46.operations_research.LocalSearchStatistics.LocalSearchFilterStatistics\x12\x1b\n\x13total_num_neighbors\x18\x03 \x01(\x03\x12$\n\x1ctotal_num_filtered_neighbors\x18\x04 \x01(\x03\x12$\n\x1ctotal_num_accepted_neighbors\x18\x05 \x01(\x03\x1a\xaf\x01\n\x1dLocalSearchOperatorStatistics\x12\x1d\n\x15local_search_operator\x18\x01 \x01(\t\x12\x15\n\rnum_neighbors\x18\x02 \x01(\x03\x12\x1e\n\x16num_filtered_neighbors\x18\x03 \x01(\x03\x12\x1e\n\x16num_accepted_neighbors\x18\x04 \x01(\x03\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\x01\x1a|\n\x1bLocalSearchFilterStatistics\x12\x1b\n\x13local_search_filter\x18\x01 \x01(\t\x12\x11\n\tnum_calls\x18\x02 \x01(\x03\x12\x13\n\x0bnum_rejects\x18\x03 \x01(\x03\x12\x18\n\x10\x64uration_seconds\x18\x04 \x01(\x01\"\x8d\x01\n\x1a\x43onstraintSolverStatistics\x12\x14\n\x0cnum_branches\x18\x01 \x01(\x03\x12\x14\n\x0cnum_failures\x18\x02 \x01(\x03\x12\x15\n\rnum_solutions\x18\x03 \x01(\x03\x12\x12\n\nbytes_used\x18\x04 \x01(\x03\x12\x18\n\x10\x64uration_seconds\x18\x05 \x01(\x01\"\xb6\x01\n\x10SearchStatistics\x12K\n\x17local_search_statistics\x18\x01 \x01(\x0b\x32*.operations_research.LocalSearchStatistics\x12U\n\x1c\x63onstraint_solver_statistics\x18\x02 \x01(\x0b\x32/.operations_research.ConstraintSolverStatisticsBI\n#com.google.ortools.constraintsolverP\x01\xaa\x02\x1fGoogle.OrTools.ConstraintSolverb\x06proto3'
)




_LOCALSEARCHSTATISTICS_LOCALSEARCHOPERATORSTATISTICS = _descriptor.Descriptor(
  name='LocalSearchOperatorStatistics',
  full_name='operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_search_operator', full_name='operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics.local_search_operator', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_neighbors', full_name='operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics.num_neighbors', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_filtered_neighbors', full_name='operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics.num_filtered_neighbors', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_accepted_neighbors', full_name='operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics.num_accepted_neighbors', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_seconds', full_name='operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics.duration_seconds', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=604,
)

_LOCALSEARCHSTATISTICS_LOCALSEARCHFILTERSTATISTICS = _descriptor.Descriptor(
  name='LocalSearchFilterStatistics',
  full_name='operations_research.LocalSearchStatistics.LocalSearchFilterStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_search_filter', full_name='operations_research.LocalSearchStatistics.LocalSearchFilterStatistics.local_search_filter', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_calls', full_name='operations_research.LocalSearchStatistics.LocalSearchFilterStatistics.num_calls', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_rejects', full_name='operations_research.LocalSearchStatistics.LocalSearchFilterStatistics.num_rejects', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_seconds', full_name='operations_research.LocalSearchStatistics.LocalSearchFilterStatistics.duration_seconds', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=606,
  serialized_end=730,
)

_LOCALSEARCHSTATISTICS = _descriptor.Descriptor(
  name='LocalSearchStatistics',
  full_name='operations_research.LocalSearchStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_search_operator_statistics', full_name='operations_research.LocalSearchStatistics.local_search_operator_statistics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_search_filter_statistics', full_name='operations_research.LocalSearchStatistics.local_search_filter_statistics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_num_neighbors', full_name='operations_research.LocalSearchStatistics.total_num_neighbors', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_num_filtered_neighbors', full_name='operations_research.LocalSearchStatistics.total_num_filtered_neighbors', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_num_accepted_neighbors', full_name='operations_research.LocalSearchStatistics.total_num_accepted_neighbors', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LOCALSEARCHSTATISTICS_LOCALSEARCHOPERATORSTATISTICS, _LOCALSEARCHSTATISTICS_LOCALSEARCHFILTERSTATISTICS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=730,
)


_CONSTRAINTSOLVERSTATISTICS = _descriptor.Descriptor(
  name='ConstraintSolverStatistics',
  full_name='operations_research.ConstraintSolverStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_branches', full_name='operations_research.ConstraintSolverStatistics.num_branches', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_failures', full_name='operations_research.ConstraintSolverStatistics.num_failures', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num_solutions', full_name='operations_research.ConstraintSolverStatistics.num_solutions', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes_used', full_name='operations_research.ConstraintSolverStatistics.bytes_used', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duration_seconds', full_name='operations_research.ConstraintSolverStatistics.duration_seconds', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=874,
)


_SEARCHSTATISTICS = _descriptor.Descriptor(
  name='SearchStatistics',
  full_name='operations_research.SearchStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_search_statistics', full_name='operations_research.SearchStatistics.local_search_statistics', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='constraint_solver_statistics', full_name='operations_research.SearchStatistics.constraint_solver_statistics', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=877,
  serialized_end=1059,
)

_LOCALSEARCHSTATISTICS_LOCALSEARCHOPERATORSTATISTICS.containing_type = _LOCALSEARCHSTATISTICS
_LOCALSEARCHSTATISTICS_LOCALSEARCHFILTERSTATISTICS.containing_type = _LOCALSEARCHSTATISTICS
_LOCALSEARCHSTATISTICS.fields_by_name['local_search_operator_statistics'].message_type = _LOCALSEARCHSTATISTICS_LOCALSEARCHOPERATORSTATISTICS
_LOCALSEARCHSTATISTICS.fields_by_name['local_search_filter_statistics'].message_type = _LOCALSEARCHSTATISTICS_LOCALSEARCHFILTERSTATISTICS
_SEARCHSTATISTICS.fields_by_name['local_search_statistics'].message_type = _LOCALSEARCHSTATISTICS
_SEARCHSTATISTICS.fields_by_name['constraint_solver_statistics'].message_type = _CONSTRAINTSOLVERSTATISTICS
DESCRIPTOR.message_types_by_name['LocalSearchStatistics'] = _LOCALSEARCHSTATISTICS
DESCRIPTOR.message_types_by_name['ConstraintSolverStatistics'] = _CONSTRAINTSOLVERSTATISTICS
DESCRIPTOR.message_types_by_name['SearchStatistics'] = _SEARCHSTATISTICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LocalSearchStatistics = _reflection.GeneratedProtocolMessageType('LocalSearchStatistics', (_message.Message,), {

  'LocalSearchOperatorStatistics' : _reflection.GeneratedProtocolMessageType('LocalSearchOperatorStatistics', (_message.Message,), {
    'DESCRIPTOR' : _LOCALSEARCHSTATISTICS_LOCALSEARCHOPERATORSTATISTICS,
    '__module__' : 'ortools.constraint_solver.search_stats_pb2'
    # @@protoc_insertion_point(class_scope:operations_research.LocalSearchStatistics.LocalSearchOperatorStatistics)
    })
  ,

  'LocalSearchFilterStatistics' : _reflection.GeneratedProtocolMessageType('LocalSearchFilterStatistics', (_message.Message,), {
    'DESCRIPTOR' : _LOCALSEARCHSTATISTICS_LOCALSEARCHFILTERSTATISTICS,
    '__module__' : 'ortools.constraint_solver.search_stats_pb2'
    # @@protoc_insertion_point(class_scope:operations_research.LocalSearchStatistics.LocalSearchFilterStatistics)
    })
  ,
  'DESCRIPTOR' : _LOCALSEARCHSTATISTICS,
  '__module__' : 'ortools.constraint_solver.search_stats_pb2'
  # @@protoc_insertion_point(class_scope:operations_research.LocalSearchStatistics)
  })
_sym_db.RegisterMessage(LocalSearchStatistics)
_sym_db.RegisterMessage(LocalSearchStatistics.LocalSearchOperatorStatistics)
_sym_db.RegisterMessage(LocalSearchStatistics.LocalSearchFilterStatistics)

ConstraintSolverStatistics = _reflection.GeneratedProtocolMessageType('ConstraintSolverStatistics', (_message.Message,), {
  'DESCRIPTOR' : _CONSTRAINTSOLVERSTATISTICS,
  '__module__' : 'ortools.constraint_solver.search_stats_pb2'
  # @@protoc_insertion_point(class_scope:operations_research.ConstraintSolverStatistics)
  })
_sym_db.RegisterMessage(ConstraintSolverStatistics)

SearchStatistics = _reflection.GeneratedProtocolMessageType('SearchStatistics', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHSTATISTICS,
  '__module__' : 'ortools.constraint_solver.search_stats_pb2'
  # @@protoc_insertion_point(class_scope:operations_research.SearchStatistics)
  })
_sym_db.RegisterMessage(SearchStatistics)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
