[tool.poetry]
name = "earthdata"
version = "0.1.1-alpha.6"
description = "Client library for NASA Earthdata APIs"
authors = ["Luis Lopez <betolin@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.5.1"
python-benedict = "^0.24.2"
python-cmr = "^0.4.1"
requests = "^2.26.0"
s3fs = "^2021.8.1"
pqdm = "^0.1.0"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
black = "^20.8b1"
isort = "^5.0.5"
ipdb = "^0.13.9"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pre-commit = "^2.4.0"
pytest = "^6.0.1"
pytest-cov = "^2.8.1"
pytest-watch = "^4.2.0"
mkdocs = "^1.1"
mkdocs-material = "^6.0.1"
markdown-include = "^0.6.0"
jupyterlab = "^3.1.10"
s3fs = "^2021.8.1"
xarray = "^0.19.0"
ipyleaflet = "^0.14.0"
responses = "^0.14.0"
dask = "^2021.9.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
