[tool.poetry]
name = "aoquality"
version = "0.2.2"
description = "Python module to access Measurement Sets' quality statistics produced by aoflagger, aoquality or DPPP."
authors = ["\"Florent Mertens\" <\"florent.mertens@gmail.com\">"]
repository = "https://gitlab.com/flomertens/aoquality/"
readme = 'README.md'
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"
matplotlib = "^3.1"
python-casacore = "^3.0"
click = "^7.0"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
aostats = "aoquality.tools.aostats:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
