#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['hikari_shim']

package_data = \
{'': ['*'],
 'hikari_shim': ['.mypy_cache/*',
                 '.mypy_cache/3.9/*',
                 '.mypy_cache/3.9/_typeshed/*',
                 '.mypy_cache/3.9/aiohttp/*',
                 '.mypy_cache/3.9/async_timeout/*',
                 '.mypy_cache/3.9/asyncio/*',
                 '.mypy_cache/3.9/attr/*',
                 '.mypy_cache/3.9/collections/*',
                 '.mypy_cache/3.9/colorlog/*',
                 '.mypy_cache/3.9/concurrent/*',
                 '.mypy_cache/3.9/concurrent/futures/*',
                 '.mypy_cache/3.9/ctypes/*',
                 '.mypy_cache/3.9/discord/*',
                 '.mypy_cache/3.9/discord/types/*',
                 '.mypy_cache/3.9/discord/ui/*',
                 '.mypy_cache/3.9/discord/webhook/*',
                 '.mypy_cache/3.9/email/*',
                 '.mypy_cache/3.9/hikari/*',
                 '.mypy_cache/3.9/hikari/api/*',
                 '.mypy_cache/3.9/hikari/events/*',
                 '.mypy_cache/3.9/hikari/impl/*',
                 '.mypy_cache/3.9/hikari/interactions/*',
                 '.mypy_cache/3.9/hikari/internal/*',
                 '.mypy_cache/3.9/hikari_shim/*',
                 '.mypy_cache/3.9/html/*',
                 '.mypy_cache/3.9/http/*',
                 '.mypy_cache/3.9/importlib/*',
                 '.mypy_cache/3.9/json/*',
                 '.mypy_cache/3.9/logging/*',
                 '.mypy_cache/3.9/multidict/*',
                 '.mypy_cache/3.9/multiprocessing/*',
                 '.mypy_cache/3.9/os/*',
                 '.mypy_cache/3.9/urllib/*',
                 '.mypy_cache/3.9/yarl/*']}

install_requires = \
['hikari']

extras_require = \
{'dev': ['discord.py', 'mypy', 'isort', 'black']}

setup(name='hikari_shim',
      version='1.0.3',
      description='A compatability shim between Discord.py and Hikari.',
      author=None,
      author_email='A5rocks <git@helvetica.moe>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.8',
     )
