#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2021/9/7 10:58 下午
# @Author : LeiXueWei
# @CSDN/Juejin/Wechat: 雷学委
# @XueWeiTag: CodingDemo
# @File : main.py.py
# @Project : renxianqi


"""
generated by PypiSeed(PPC) - Main Program
"""


import renxianqi.name_checker as nc

def main():
    nc.about()
    nc.app_start()


if __name__ == "__main__":
    main()
