
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T16:08:25+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4d3f230e8cf9fb836122ddcb2b54eabd1982ab9d",
 "version": "v0.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
