
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-07T18:03:03-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "668c3eabc4af00fb873bbaa2a3a0d5843bf160a4",
 "version": "0.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
