
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T11:24:49+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2b56ef8a158cc7fbe523cbd1c02f13cff8682e5",
 "version": "0.2.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
