[tool.poetry]
name = "typety"
version = "0.0.2"
description = ""
authors = ["Dragonlord1005"]
homepage = "https://github.com/Dragonlord1005/typety"
packages = [
  { include = "typety" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
