name: tutorials

on:
  push:
    branches: [master,dev,paparazzi]
  pull_request:
    branches: [master]

jobs:
  notebooks:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pymc-version: "pymc3==3.9.3"
            arviz-version: "arviz==0.11.1"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.pymc-version }}-

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry
          environment-file: environment.yml

      - name: Set up environment
        shell: bash -l {0}
        run: |
          jupyter nbextension enable --py widgetsnbextension

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip install ${{ matrix.pymc-version }} ${{ matrix.arviz-version }} pymc3-ext
          python -m pip install -U sympy
          python -m pip install -U corner
          python -m pip install -U batman-package
          python -m pip install -e ".[docs]"

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          cd notebooks
          python run_notebooks.py

      - uses: actions/upload-artifact@v2
        with:
          name: notebooks-for-${{ github.sha }}
          path: notebooks

      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1.0.0
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
