[tool.poetry]
name = "projectaile"
version = "0.0.1"
description = "A framework agnostic architecture and utility library for all machine learning and deep learning projects providing an abstract and easy to use but still very configurable API."
authors = ["abtExp <abt.exp@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
