# Generated by Django 3.2.5 on 2021-09-04 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('delivery_time', models.CharField(choices=[('by11', 'by 11.00 AM'), ('by11.15', 'by 11.00 AM'), ('by11.30', 'by 11.30 AM'), ('by11.45', 'by 11.45 AM'), ('by12.00', ']by 12.00 PM'), ('by12.15', 'by 12.15 PM'), ('by12.30', 'by 12.30 PM'), ('by12.45', 'by 12.45 PM'), ('by1.00', 'by 1.00  PM')], max_length=100)),
                ('type_of_order', models.CharField(choices=[('Hand it to me', 'Hand it to me'), ('Leave it at my door', 'Leave it at my door')], max_length=100)),
                ('city', models.CharField(choices=[('bapatla', 'Bapatla'), ('charala', 'Chirala'), ('guntur', 'Guntur'), ('ongole', 'Ongole'), ('nellore', 'Nellore')], max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('Pay with cash to the courier', 'Pay with cash to the courier'), ('Online payment', 'Online Payment')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_items_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='order_menu_page/')),
                ('item_title', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=100)),
                ('item_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium.'), ('standard', 'Standars'), ('large', 'Large'), ('thin', 'Thin')], default='select', max_length=20)),
                ('item_cost', models.FloatField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_item_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='images_app2/')),
                ('item_title', models.CharField(max_length=100)),
                ('item_price', models.FloatField(default=0)),
                ('item_quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('slug', models.SlugField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp3.order_items_menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='webapp3.Order_item_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
