
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-12T15:51:07+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9329dea7d05aabb02d839be017cd9ddc2fd46a45",
 "version": "0.4.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
