[build-system]
requires = ['pip', 'setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-grid<=v2.8.0.2', 'fenics-ufl==2019.1.0', 'dune-alugrid<=v2.8.0.2', 'dune-istl<=v2.8.0.2', 'dune-localfunctions<=v2.8.0.2']
build-backend = 'setuptools.build_meta'
