# Generated by Django 3.2.8 on 2021-10-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubOauthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='Refresh Token')),
                ('expires_in', models.CharField(max_length=255, verbose_name='Expires In')),
                ('expires_in_dt', models.DateTimeField(max_length=255, verbose_name='Expires In DT')),
            ],
            options={
                'verbose_name': 'Hub Oauth Token',
                'verbose_name_plural': 'Hub Oauth Tokens',
                'db_table': 'hub_oauth_token',
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_uuid', models.UUIDField(verbose_name='Hub Company UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Hub Company Name')),
            ],
            options={
                'verbose_name': 'User Company',
                'verbose_name_plural': 'User Companys',
                'db_table': 'hub_companies',
            },
        ),
        migrations.CreateModel(
            name='HubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='django_hub_sdk.huboauthtoken', verbose_name='Tokens')),
            ],
            options={
                'verbose_name': 'HubUser',
                'verbose_name_plural': 'HubUsers',
                'db_table': 'hub_users',
            },
        ),
    ]
