
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-18T11:02:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae4f54726a34f95532d235ad5ef848805dfda1b4",
 "version": "1.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
