[tool.poetry]
name = "repl_python3_test-senpai"
version = "0.1.0"
description = ""
authors = ["4gboframram <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
lark = "^0.11.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
