name: c3dev
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - mpi4py
  - nb_conda_kernels
  - nodejs
  - pillow
  - pip
  - plotly-orca
  - psutil
  - python>=3.6
  - scipy
  - pip:
    - --editable ./[dev]
    - tox-gh-actions
    - sphinx-gallery
    - sphinx_bootstrap_theme