[tool.poetry]
name = "redcap_client"
version = "0.1.2"
description = "A fork of seattleflu/id3c containing only the redcap Project client"
authors = ["Tom Thorogood <goodtom@uw.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.2,<3.10"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
