# Generated by Django 3.1.12 on 2021-10-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factorial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fhemployee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
