#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['swissparlpy']

package_data = \
{'': ['*']}

install_requires = \
['requests', 'pyodata']

extras_require = \
{'dev': ['flit', 'jupyter', 'pandas'],
 'test': ['flake8', 'mock', 'responses', 'pytest', 'pytest-cov']}

setup(name='swissparlpy',
      version='0.2.0',
      description='Client for Swiss parliament API',
      author=None,
      author_email='Stefan Oderbolz <odi@metaodi.ch>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
