[tool.poetry]
name = "redcap_client"
version = "0.1.1"
description = "A fork of seattleflu/id3c containing only the redcap Project client"
authors = ["Tom Thorogood <tom@tomthorogood.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.2,<3.10"

[tool.poetry.dev-dependencies]
twine = "^3.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
