[tool.poetry]
name = "eir-dl"
version = "0.1.17-alpha"
description = ""
license = "AGPLv3"
authors = ["Arnor Sigurdsson"]
packages = [
    { include="eir", from="." },
]

[tool.poetry.dependencies]
python = ">= 3.8,< 3.10"
pandas = "^1.2.0"
numpy = "^1.19.2"
torch = "^1.9.1"
torchvision = "^0.10.1"
py = "^1.9.0"
matplotlib = "^3.3.2"
pytorch-ignite = "^0.4.2"
tqdm = "^4.55.0"
sympy = "^1.6.2"
scikit-learn = "^0.24.0"
seaborn = "^0.11.1"
joblib = "^0.17.0"
tensorboard = "^2.3.0"
ConfigArgParse = "^1.2.3"
plotly = "^4.11.0"
torch-optimizer = "^0.1.0"
adabelief-pytorch = "^0.2.0"
dill = "^0.3.3"
hypothesis = "^6.14.0"
aislib = "^0.1.6-alpha.0"
colorama = "^0.4.4"
ipython = "^7.26.0"
torchtext = "^0.10.1"
shap = "^0.39.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.1"
tox = "^3.20.1"
flake8 = "^3.8.4"
jupyter = "^1.0.0"
ipykernel = "^5.3.4"
coverage = "^5.3"
snakeviz = "^2.1.0"
pytest-cov = "^2.10.1"
pytest-testmon = "^1.0.3"
pynvim = "^0.4.2"
visidata = "^2.0.1"
pre-commit = "^2.7.1"
gpustat = "^0.6.0"
pyinstaller = "^4.0"
black = "^21.5b2"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"
sphinx-copybutton = "^0.3.3"
tomlkit = "^0.7.2"


[tool.poetry.scripts]
eirtrain = "eir.train:main"
eirpredict = "eir.predict:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
