
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T11:11:22-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2720d29ec25a2db5569f7be7c5297c7af7176137",
 "version": "2021.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
