
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T18:19:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "533ec3b7ce48bbc9795880a9fcede24b8ad9d571",
 "version": "0.7.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
