
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-12T17:23:14+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "a6c5b169f10bb9c3fa1eade6443e6cc876bf98f2",
 "version": "3.7.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
