
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T19:15:47-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0d07ab9a87a9f44e65b1a6b4481841eed48deb9",
 "version": "2021.10.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
