
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-18T11:25:59+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a825b481c75e5bab31aa630ab02f835e064b5ee3",
 "version": "1.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
