name: cogent3
channels:
  - plotly
  - conda-forge
dependencies:
  - pandoc
  - python=3.7
  - matplotlib
  - plotly
  - plotly-orca
  - pip
  - pip:
    - numpydoc
    - psutil
    - pillow
    - ipython
    - ipykernel
    - ipywidgets
    - sphinx>=1.6
    - nbsphinx
    - nbformat
    - nbconvert!=5.4
    - sphinxcontrib-bibtex
    - sphinx-gallery
    - sphinx_bootstrap_theme
    - ../
