all:
  hosts: {}
  children:
    kube_control_plane:
      hosts: {}
    kube_node:
      hosts: {}
    etcd:
      hosts: {}
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
