[tool.poetry]
name = "pyaffine"
version = "0.1.5"
description = ""
authors = ["davidshivaji <davidshivaji@gmail.com>"]

[tool.poetry.scripts]
affine = "affine:main"

[tool.poetry.dependencies]
python = "^3.9"
python-datamuse = "1.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
