
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-12T11:11:08+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b682d02889bf957e3101cc4f85a071ca8036147",
 "version": "0.7.1.post.dev72"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
