[tool.poetry]
name = "drop-duplicates-in-pd-column"
version = "0.1.1"
description = ""
authors = ["ilikechicken67 <thomas.staats443@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
