name: CI

on:
  pull_request:
  push:
    branches: 
    - master
    tags:
    - 'v*'

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
        runs-on:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.runs-on }}
    name: Test • 🐍 ${{ matrix.python-version }} • ${{matrix.runs-on}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install .[test]

    - name: Test package
      run: python -m pytest --forked
      
  checks_windows:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.8
        - 3.9
        runs-on:
        - windows-latest
    runs-on: ${{ matrix.runs-on }}
    name: Test • 🐍 ${{ matrix.python-version }} • ${{matrix.runs-on}}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: python -m pip install .[test]

    - name: Test package
      env:
        LIBCLANG_PATH: C:\msys64\mingw64\bin\libclang.dll
      run: python -m pytest -n2
  
  dist:
    runs-on: ubuntu-latest
    name: Build distribution
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Build
      run: pipx run build

    - uses: actions/upload-artifact@v2
      with:
        name: DistPackage
        path: dist
