[tool.poetry]
name = "lb-nightly-configuration"
version = "0.1.0"
description = "configuration of the LHCb Nightly Build System"
authors = [
    "Marco Clemencic <marco.clemencic@cern.ch>",
    "Maciej Szymanski <maciej.szymanski@cern.ch>",
    "LHCb Core Software <lhcb-core-soft@cern.ch>"
]
license = "GPL-3.0-only"
packages = [
    { include = "lb" },
]

[tool.poetry.dependencies]
python = "^3.6"
gitpython = "^3.1.3"
tabulate = "^0.8.7"
pyyaml = "^5.3.1"

[tool.poetry.scripts]
lbn-check-config = 'lb.nightly.configuration:check_config'

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}
pytest-cov = "^2.8.1"
flake8 = "^3.8.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
