
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-09T17:45:40-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "04cabf96b86347c78d816fb90a7e0c2b29a45cfb",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
