[tool.poetry]
name = "lb-nightly-db"
version = "0.1.0"
description = "Database access layer for LHCb Nightly and Continuous Integration Build System"
authors = [
    "Marco Clemencic <marco.clemencic@cern.ch>",
    "Maciej Szymanski <maciej.szymanski@cern.ch>",
    "LHCb Core Software <lhcb-core-soft@cern.ch>"
]
license = "GPL-3.0-only"
packages = [
    { include = "lb" },
]

[tool.poetry.dependencies]
python = "^3.8"
cloudant = "^2.14.0"
lb-nightly-configuration = "^0.1.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-cov = "^2.12.1"
black = {version = "^21.7b0", allow-prereleases = true}

[tool.isort]
profile = "black"
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
