#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2020  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

# ** WARNING **
# This file is auto-generated by the update_version.py script.
# ** WARNING **

version_str = "0.0.2.post76"
version_tuple = (0, 0, 2, 76)
try:
    from packaging.version import Version as V
    pversion = V("0.0.2.post76")
except ImportError:
    pass

git_hash = "3aab631902d8ab8b20b1bc7abc40df9558bce5c5"
git_describe = "v0.0.2-76-g3aab631"
git_msg = """\
commit 3aab631902d8ab8b20b1bc7abc40df9558bce5c5
Merge: 99f199f 7e6a3e3
Author: Tim Ansell <tansell@google.com>
Date:   Tue Oct 12 19:02:54 2021 -0700

    Merge pull request #73 from mithro/file-fix

    Fix pip breaking `file:` support.

"""
