[tool.poetry]
name = "clickr-logger"
version = "0.1.0"
description = "Common logger functions for clickr"
authors = ["Grzegorz Bajson <gbajson@protonmail.ch>"]

[tool.poetry.dependencies]
python = "^3.7"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
