[tool.poetry]
name = "FaceID"
version = "0.1.0"
description = "FaceID().load().search()"
authors = ["dudha369 <duduha2010@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=0.1.0"]
build-backend = "poetry.core.masonry.api"
