[tool.poetry]
name = "gcoin"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
oauth2client = "^4.1.3"
pygsheets = "^2.0.5"
setuptools = "^58.2.0"
twine = "^3.4.2"
wheel = "^0.37.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
