[tool.poetry]
name = "poetry-demo-1199"
version = "0.1.0"
description = "Demo of poetry for akashkj.com"
authors = ["Akash"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.26.0"
mypy = "^0.910"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
