[tool.poetry]
name = "melter"
version = "0.3.0"
description = "Identifies unsolved cases that should be analysed again"
authors = ["Henning Onsbring"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.12.1"
myst-nb = "^0.13.0"
sphinx-autoapi = "^1.8.4"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=58.0.4", "toml>=0.10.2", "Click>=0.5.3"]
build-backend = "poetry.core.masonry.api"
