# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tensorboard/compat/proto/coordination_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorboard/compat/proto/coordination_service.proto',
  package='tensorboard',
  syntax='proto3',
  serialized_options=_b('ZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto'),
  serialized_pb=_b('\n3tensorboard/compat/proto/coordination_service.proto\x12\x0btensorboard\"\xb0\x01\n\x1a\x43oordinationServiceConfigs\x12\x14\n\x0cservice_type\x18\x01 \x01(\t\x12\x16\n\x0eservice_leader\x18\x02 \x01(\t\x12\x1b\n\x13\x65nable_health_check\x18\x03 \x01(\x08\x12&\n\x1e\x63luster_register_timeout_in_ms\x18\x04 \x01(\x03\x12\x1f\n\x17heartbeat_timeout_in_ms\x18\x05 \x01(\x03\x42WZUgithub.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_protob\x06proto3')
)




_COORDINATIONSERVICECONFIGS = _descriptor.Descriptor(
  name='CoordinationServiceConfigs',
  full_name='tensorboard.CoordinationServiceConfigs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_type', full_name='tensorboard.CoordinationServiceConfigs.service_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_leader', full_name='tensorboard.CoordinationServiceConfigs.service_leader', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enable_health_check', full_name='tensorboard.CoordinationServiceConfigs.enable_health_check', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cluster_register_timeout_in_ms', full_name='tensorboard.CoordinationServiceConfigs.cluster_register_timeout_in_ms', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat_timeout_in_ms', full_name='tensorboard.CoordinationServiceConfigs.heartbeat_timeout_in_ms', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=245,
)

DESCRIPTOR.message_types_by_name['CoordinationServiceConfigs'] = _COORDINATIONSERVICECONFIGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoordinationServiceConfigs = _reflection.GeneratedProtocolMessageType('CoordinationServiceConfigs', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATIONSERVICECONFIGS,
  '__module__' : 'tensorboard.compat.proto.coordination_service_pb2'
  # @@protoc_insertion_point(class_scope:tensorboard.CoordinationServiceConfigs)
  })
_sym_db.RegisterMessage(CoordinationServiceConfigs)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
