
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T06:42:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "171bf7c0d1850a96c4594b4defb44086e8f838fd",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
