dic = {"a":"c",
       "b":"d",
       "c":"e",
       "d":"f",
       "e":"g",
       "f":"h",
       "g":"i",
       "h":"j",
       "i":"k",
       "j":"l",
       "k":"m",
       "l":"n",
       "m":"o",
       "n":"p",
       "o":"q",
       "p":"r",
       "q":"s",
       "r":"t",
       "s":"u",
       "t":"v",
       "u":"w",
       "v":"x",
       "w":"y",
       "x":"z",
       "y":"a",
       "z":"b",
       ".":"`",
       "A":"D",
       "B":"E",
       "C":"F",
       "D":"G",
       "E":"H",
       "F":"I",
       "G":"J",
       "H":"K",
       "I":"L",
       "J":"M",
       "K":"N",
       "L":"O",
       "M":"P",
       "N":"Q",
       "O":"R",
       "P":"S",
       "Q":"T",
       "R":"U",
       "S":"V",
       "T":"W",
       "U":"X",
       "V":"Y",
       "W":"Z",
       "X":"A",
       "Y":"B",
       "Z":"C",
       ",":"<",
       " ":">",
       "(":"/",
       ")":"?",
       ":":";",
       "!":"[",
       "@":"]",
       "#":"{",
       "$":"}",
       "%":"!",
       "^":"@",
       "&":"#",
       ":":"$",
       "1":"%",
       "2":"^",
       "3":"&",
       "4":"*",
       "5":"+",
       "6":"=",
       "7":"\\",
       "8":"|",
       "9":"'",
       "0":"-",
       "-":","}
def Encrypt(name):
    for i in name:
        if i in dic:
            i = dic[i]
            print(i, end='')
    
def Decrypt(name):
    for i in name:
        val = list(dic.keys())
        val_list = list(dic.values())
        position = val_list.index(i)
        print(val[position], end='')
        

