
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T15:39:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "701b33623c94fbe58c1caf0af15d994e2626c35a",
 "version": "2021.10.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
