---
networks:
  private:
    name: private
  public:
    name: public
services:
  caddy:
    build: services/caddy
    container_name: caddy
    env_file: .env
    labels:
      kompose.volume.size: 5Gi
      kompose.volume.storage-class-name: openebs-jiva-csi-default
    networks:
      - public
      - private
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_conf:/config
      - caddy_data:/data
version: '3.7'
volumes:
  caddy_conf: null
  caddy_data: null
