[project]
name = "navigator"
authors = [
    {name = "Jesus Lara G.", email = "jesuslarag@gmail.com"},
]
readme = "README.md"
classifiers = [
    "License :: OSI Approved :: BSD License",
]
requires-python = ">=3.8"
dynamic = ['version', 'description']

[build-system]
requires = [
    "setuptools>=47",
    "wheel==0.36.2",
    "Cython==0.29.21",
    "numpy==1.19.4",
    "asyncio==3.4.3"
]

build-backend = "setuptools.build_meta"
