services:
    ebel:
        build: .
        restart: always
        container_name: bikmi_ebel
        ports: 
            - 5000:5000
        networks:
            - bikmi
        depends_on:
            - mysql
            - orientdb
        volumes:
            - bikmi_ebel_data:/root/.ebel/
    mysql:
        image: mysql:8.0.24
        restart: always
        container_name: bikmi_mysql
        ports:
            - 3606:3606
        environment: 
            MYSQL_ROOT_PASSWORD: ebel
            MYSQL_USER: ebel
            MYSQL_PASSWORD: ebel
            MYSQL_DATABASE: ebel
        networks:
            - bikmi
        volumes:
            - bikmi_mysql:/var/lib/mysql
    orientdb:
        image: orientdb:3.2.0
        restart: always
        container_name: bikmi_orientdb
        environment:
            - ORIENTDB_ROOT_PASSWORD=ebel
        ports:           
            - 2424:2424
            - 2480:2480
        networks:
            - bikmi    
        volumes: 
            - bikmi_orientdb_db:/orientdb/databases
            - bikmi_orientdb_backup:/orientdb/backup
            - bikmi_orientdb_config:/orientdb/config
    phpmyadmin:
        image: phpmyadmin:5.1.0
        restart: always
        container_name: bikmi_phpmyadmin
        ports:
            - 8089:80
        networks:
            - bikmi
        environment:
            - PMA_ARBITRARY=1
networks:
    bikmi:
        driver: bridge
volumes:
    bikmi_orientdb_db:
    bikmi_orientdb_backup:
    bikmi_mysql:
    bikmi_orientdb_config:
    bikmi_ebel_data: