class Types:
    ENGINE_AUDIO = "Engine Audio"
    PLAYER_BANNER = "Player Banner"
    BODY = "Body"
    TOPPER = "Topper"
    GOAL_EXPLOSION = "Goal Explosion"
    WHEELS = "Wheels"
    PLAYER_ANTHEM = "Player Anthem"
    ANIMATED_DECAL = "Animated Decal"
    PAINT_FINISH = "Paint Finish"
    BLUEPRINT = "Blueprint"
    DECAL = "Decal"
    AVATAR_BORDER = "Avatar Border"
    ANTENNA = "Antenna"
    ROCKET_BOOST = "Rocket Boost"
    PLAYER_TITLE = "Player Title"
    TRAIL = "Trail"
