[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "rsskey"
version = "0.0.1"
description = "RSS feed mirror on Misskey"
readme = "README.md"
requires-python = ">=3.6"
license = { file = "COPYING" }
authors = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
maintainers = [ { name = "Nguyễn Gia Phong", email = "mcsinyx@disroot.org" } ]
keywords = [ "rss", "misskey" ]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python" ]
dependencies = [
    "feedparser", "httpx", "loca", "markdownify", "python-dateutil", "trio" ]
urls = { project = "https://sr.ht/~cnx/rsskey" }
