# Generated by Django 3.2.5 on 2021-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cusine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_pic', models.FileField(upload_to='uploads/')),
                ('cu_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='hash email')),
                ('user_hash_key', models.CharField(max_length=64, verbose_name='hash key')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pic', models.ImageField(upload_to='images/')),
                ('item_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.CharField(max_length=10000)),
                ('pro_email', models.EmailField(max_length=254)),
                ('pro_description', models.TextField()),
                ('pro_status', models.CharField(blank=True, default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PtCf_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat', models.ImageField(upload_to='pc_data/')),
                ('head', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('link_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Top_rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_img', models.ImageField(upload_to='to_rest/')),
            ],
        ),
    ]
