# -*- coding: utf-8 -*-

"""
coingeckoapiv3testing

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from tests.http_response_catcher import HttpResponseCatcher
from coingeckoapiv3testing.api_helper import APIHelper
from coingeckoapiv3testing.controllers.indexes_controller import IndexesController


class IndexesControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(IndexesControllerTests, cls).setUpClass()
        cls.response_catcher = HttpResponseCatcher()
        cls.controller = IndexesController(cls.config, cls.response_catcher)

    # List all market indexes
    def test_listallmarketindexes(self):
        # Parameters for the API call
        per_page = None
        page = None

        # Perform the API call through the SDK function
        self.controller.listallmarketindexes(per_page, page)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

    # list market indexes id and name
    def test_listmarketindexesidandname(self):

        # Perform the API call through the SDK function
        self.controller.listmarketindexesidandname()

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

