
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T11:46:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "97c5534d5128984d9f2bd6e90675924be2df9e31",
 "version": "1.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
