
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-18T16:48:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b239cf9adb452725703d189d5a5b3591affdc252",
 "version": "0.4.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
