[tool.poetry]
name = "alchemer"
version = "0.5.3"
description = ""
authors = ["Charlie Bini <5003326+cbini@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
python-dateutil = "^2.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black = "^21.9b0"
python-dotenv = "^0.19.1"
pytest-dotenv = "^0.5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
