
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-11T15:16:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cfbb1e11addefc96fdf848e0940040f7ffc0dbe7",
 "version": "0.25.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
