[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Michael Schock <m@mjschock.com>"]
description = "The datagrep CLI."
name = "datagrep"
readme = "README.md"
version = "3.0.1-alpha.5"

[tool.poetry.dependencies]
click = ">=7.1.1,<7.2.0"
cookiecutter = "^1.7.3"
plumbum = "^1.7.0"
python = "^3.7"
typer = {extras = ["all"], version = "^0.3"}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
isort = "^5.9.3"
pytest = "^5.2"
Sphinx = "^4.2.0"
toml-sort = "^0.19.0"
typer-cli = "^0.0.12"

[tool.poetry.scripts]
datagrep = "datagrep.main:app"
dgp = "datagrep.platform.main:app"
