[tool.poetry]
name = "jaxex"
version = "0.0.1"
description = "A tool for creating science experiments in jax, torch, brax, etc"
authors = ["LSaldyt <lucassaldyt@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = ">=1.19"
gym = "^0.20.0"
Pillow = "^8.3.2"
plotly = "^5.3.1"
pybullet = "^3.1.9"
pyglet = "^1.5.21"
dm-haiku = "^0.0.4"
optax = "^0.0.9"
pandas = "^1.3.3"
dm-tree = "^0.1.6"
jax = "^0.2.21"
jaxlib = "^0.1.71"
torch = "^1.9.1"
cloudpickle = "^2.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
