apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caddy
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ cookiecutter.domain_name }}
      http:
        paths:
          - path: "/.well-known/acme-challenge"
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: caddy
                port:
                  number: 443
