# Generated by Django 3.2.7 on 2021-10-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edc_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulation',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'Formulation', 'verbose_name_plural': 'Formulations'},
        ),
        migrations.AlterModelOptions(
            name='formulationtype',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'ordering': ['display_index', 'display_name'], 'verbose_name': 'FormulationType', 'verbose_name_plural': 'FormulationTypes'},
        ),
        migrations.AlterModelOptions(
            name='historicalformulation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Formulation'},
        ),
    ]
