#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['toolip', 'toolip.fastapi']

package_data = \
{'': ['*'], 'toolip': ['utils/*']}

setup(name='toolip',
      version='0.1',
      description='A collection of python utils for webapps',
      author='Anthony Hillairet',
      author_email='ant@satel.ca',
      url='https://github.com/SatelCreative/toolip',
      packages=packages,
      package_data=package_data,
     )
