# coding: utf-8

"""
    Planetary Data System DOI Service API

    PDS API for managing DOI registration with OSTI service.  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pds.api_client
from pds.api_client.models.doi_record_all_of import DoiRecordAllOf  # noqa: E501
from pds.api_client.rest import ApiException

class TestDoiRecordAllOf(unittest.TestCase):
    """DoiRecordAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DoiRecordAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pds.api_client.models.doi_record_all_of.DoiRecordAllOf()  # noqa: E501
        if include_optional :
            return DoiRecordAllOf(
                record = '0', 
                creation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                message = '0'
            )
        else :
            return DoiRecordAllOf(
        )

    def testDoiRecordAllOf(self):
        """Test DoiRecordAllOf"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
