
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T11:56:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "08634a1dee8c9bcbca5435af2d70bcd2ab26a464",
 "version": "0.5.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
