
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-14T17:45:41+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cc2b78494b15d6d733d4532773711813e3fa82a",
 "version": "0.25.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
