[tool.poetry]
name = "jetblack-serialization"
version = "3.0.0-alpha.1"
description = "Serialization for JSON and XML using typing"
repository = "https://github.com/rob-blackbourn/jetblack-serialization"
authors = ["Rob Blackbourn <rob.blackbourn@gmail.com>"]
keywords = ['serialization', 'jetblack', 'json', 'xml', 'typing']
license = "Apache-2.0"
readme = "README.md"
packages = [
  { include = "jetblack_serialization" }
]

[tool.poetry.dependencies]
python = "^3.7"
jetblack-iso8601 = "^1.0"
lxml = "^4.6"
typing-extensions = "^3.10"
typing_inspect = "^0.7"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5"
mypy = "^0.910"
pylint = "^2.11"
pytest = "^6.2"
rope = "^0.20"
stringcase = "^1.2"
mkdocs = "^1.2"
mkdocs-material = "^7.2"
jetblack-markdown = "^0.6"
mike = "^1.1.1"
lxml-stubs = "^0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
