VERSION_YEAR = 2021
VERSION_MONTH = int('10')
VERSION_DAY = int('11')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('00')
MAJOR_VERSION = 1
MINOR_VERSION = 1
PATCH_VERSION = 202110110900
version_date = '2021/10/11 09:00'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
