
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T18:43:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "888babc4d0e8676172e07e3a7ca456f50df903f8",
 "version": "2021.10.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
