[build-system]
requires = [
    "packaging>=21.0; platform_machine=='arm64'",
    "setuptools",
    "wheel",
    "Cython>=0.29.24,<3.0",
    "numpy==1.16.6; python_version<='3.7'",
    "numpy==1.17.5; python_version=='3.8'",
    "numpy==1.19.5; python_version=='3.9'",
    "numpy; python_version>='3.10'",
    "numpy>=1.14"
]
