exclude: 'doc/conf.py'

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
        args: [--remove]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-deprecated, flake8-mutable]

-   repo: https://github.com/PyCQA/isort/
    rev: 5.9.3
    hooks:
    -   id: isort

-   repo: local
    hooks:
    -   id: rstcheck
        name: rstcheck
        entry: rstcheck
        files: '.rst'
        language: python
        additional_dependencies: [rstcheck, sphinx]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal

-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        files: '.py|.rst'
        exclude: 'doc/doc_examples_to_gallery.py'
        # escaped characters currently do not work correctly
        # so \nnumber is considered a spelling error....
        args: [-L nnumber]

-   repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
    -   id: yesqa
