[tool.poetry]
name = "dizzle"
version = "0.2.1"
description = "Tools to normalize and interact with data of various formats."
authors = ["4thel00z <4thel00z@gmail.com>"]
license = "GPL-3"
readme = "README.md"
homepage = "https://github.com/4thel00z/dizzle"
packages = [
    { include = "dizzle" },
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
orjson = "^3.6.4"
python-dotenv = "^0.19.0"
icecream = "^2.1.1"
SQLAlchemy = "^1.4.25"
pandas = "^1.3.3"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
pytest = "^6.2.5"
ptpython = "^3.0.20"
neovim = "^0.3.1"
pdbpp = "^0.10.3"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
