# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ortools/sat/cp_model_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ortools.sat import cp_model_pb2 as ortools_dot_sat_dot_cp__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ortools/sat/cp_model_service.proto',
  package='operations_research.sat.v1',
  syntax='proto3',
  serialized_options=b'\n\031com.google.ortools.sat.v1B\023CpModelServiceProtoP\001\252\002\022Google.OrTools.Sat',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"ortools/sat/cp_model_service.proto\x12\x1aoperations_research.sat.v1\x1a\x1aortools/sat/cp_model.proto\"e\n\x0f\x43pSolverRequest\x12\x34\n\x05model\x18\x01 \x01(\x0b\x32%.operations_research.sat.CpModelProto\x12\x1c\n\x14parameters_as_string\x18\x02 \x01(\t2t\n\x08\x43pSolver\x12h\n\x0cSolveProblem\x12+.operations_research.sat.v1.CpSolverRequest\x1a).operations_research.sat.CpSolverResponse\"\x00\x42G\n\x19\x63om.google.ortools.sat.v1B\x13\x43pModelServiceProtoP\x01\xaa\x02\x12Google.OrTools.Satb\x06proto3'
  ,
  dependencies=[ortools_dot_sat_dot_cp__model__pb2.DESCRIPTOR,])




_CPSOLVERREQUEST = _descriptor.Descriptor(
  name='CpSolverRequest',
  full_name='operations_research.sat.v1.CpSolverRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='operations_research.sat.v1.CpSolverRequest.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters_as_string', full_name='operations_research.sat.v1.CpSolverRequest.parameters_as_string', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=195,
)

_CPSOLVERREQUEST.fields_by_name['model'].message_type = ortools_dot_sat_dot_cp__model__pb2._CPMODELPROTO
DESCRIPTOR.message_types_by_name['CpSolverRequest'] = _CPSOLVERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CpSolverRequest = _reflection.GeneratedProtocolMessageType('CpSolverRequest', (_message.Message,), {
  'DESCRIPTOR' : _CPSOLVERREQUEST,
  '__module__' : 'ortools.sat.cp_model_service_pb2'
  # @@protoc_insertion_point(class_scope:operations_research.sat.v1.CpSolverRequest)
  })
_sym_db.RegisterMessage(CpSolverRequest)


DESCRIPTOR._options = None

_CPSOLVER = _descriptor.ServiceDescriptor(
  name='CpSolver',
  full_name='operations_research.sat.v1.CpSolver',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=197,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='SolveProblem',
    full_name='operations_research.sat.v1.CpSolver.SolveProblem',
    index=0,
    containing_service=None,
    input_type=_CPSOLVERREQUEST,
    output_type=ortools_dot_sat_dot_cp__model__pb2._CPSOLVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CPSOLVER)

DESCRIPTOR.services_by_name['CpSolver'] = _CPSOLVER

# @@protoc_insertion_point(module_scope)
