
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-11T09:30:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e2eeade2a7a4be17fbb9aff702e0bd41642c793e",
 "version": "2539"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
