[tool.poetry]
name = "django_tidyfields"
version = "1.2.1"
description = "Easily accept html input with Django models, templates and DRF serializers."
homepage = "https://gitlab.com/routh.io/python/django_tidyfields"
repository = "https://gitlab.com/routh.io/python/django_tidyfields"
authors = ["Chris Routh <chris@routh.io>"]
license = "MIT"
readme = "README.rst"
keywords = ["django", "lxml", "input", "html", "fields"]
classifiers = [
    "Framework :: Django",
    "Framework :: Django :: 2.2",
    "Framework :: Django :: 3.0",
    "Framework :: Django :: 3.1",
    "Framework :: Django :: 3.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
# These packages are mandatory and form the core of this package’s distribution.
python = ">=3.6.1,<4.0"
lxml = "4.6.3"
Django = ">=2.2"
pylint = {version = "2.11.1", optional = true}
pylint-django = {version = "2.0.8", optional = true}
sphinx = {version = ">=4.2.0", optional = true}
sphinx-rtd-theme = {version = ">=1.0.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "6.2.5"
pytest-django = "4.4.0"
pytest-cov = "3.0.0"
tox = ">=3.24.4"
isort = "5.9.3"

[tool.poetry.extras]
pylint = ["pylint", "pylint-django"]
docs = ["sphinx", "sphinx-rtd-theme"]

[build-system]
requires = ["poetry_core>=1.1.11"]
build-backend = "poetry.core.masonry.api"

[tool.aliases]
test = ["pytest"]

[tool.bdist_wheel]
universal = 1

[tool.isort]
combine_as_imports = true
default_section = "THIRDPARTY"
include_trailing_comma = false
line_length = 79
multi_line_output = 5
skip = ["venv",".tox",".history",".eggs"]
# skip_glob =
not_skip = "__init__.py"
known_django="django"
known_first_party="django_tidyfields"
sections=[
    "FUTURE",
    "STDLIB",
    "DJANGO",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]

