
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-12T16:27:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7122b606c92aedc097284a4be9067244f67aef10",
 "version": "1.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
