
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-18T13:58:23-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d9db10eb98832b742cb3b27b2d4aafb7449e5a4",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
