
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-14T08:56:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "750ea91235c4d901aa6cfda94bcae8abf9a9db5f",
 "version": "2021.10.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
