[tool.poetry]
name = "pyaffine"
version = "0.1.4"
description = ""
authors = ["davidshivaji <davidshivaji@gmail.com>"]

[tool.poetry.scripts]
affine = "__main__:run"

[tool.poetry.dependencies]
python = "^3.9"
python-datamuse = "1.3.0"


[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
