# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['django_filter_groups', 'django_filter_groups.templatetags']

package_data = \
{'': ['*'],
 'django_filter_groups': ['static/django_filter_groups/*', 'templates/*']}

install_requires = \
['Django>=2', 'django-filter>=2.4.0']

setup_kwargs = {
    'name': 'django-filter-groups',
    'version': '0.2.0',
    'description': '',
    'long_description': "# django filter groups\n\nThis package groups filters generated by django-filter\nThe main reason to use it - don't show all filters (show only selected filters)\n\n## how to use\n```\npip install django-filter-grouped\n```\nadd to your `INSTALLED_APPS` after `django-filter`\n\nuse it in your template `{% filters_by_groups %}`\n\nif FilterSet name is not 'filter' -> add filterset name\n`{% filters_by_groups my_custom_filterset %}`\n",
    'author': 'pnoryk',
    'author_email': 'pnoryk@mail.ru',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/PNoryk/django-filter-groups',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'python_requires': '>=3.6.1,<4.0.0',
}


setup(**setup_kwargs)
