[tool.poetry]
name = "pysshm"
version = "0.3.3"
description = "SSM shell client, the python way"
authors = ["Pierre-Yves Gillier <github@pygillier.me>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/pygillier/pysshm"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console :: Curses",
    "Intended Audience :: System Administrators",
    "Operating System :: OS Independent",
    "Topic :: System :: Shells"
]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.18.58"
click = "^8.0.3"
loguru = "^0.5.3"
pick = "^1.0.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
pylint = "^2.11.1"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
pysshm = "pysshm.cli:run"
