
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T03:23:37+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "c49d607ca59532dc3609a6045acafdedc2c4206c",
 "version": "1.84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
