[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "installer"
author = "Pradyun Gedam"
author-email = "pradyunsg@gmail.com"
home-page = "https://github.com/pradyunsg/installer"
description-file = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
requires-python = ">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"
requires = [
  "configparser >= 3.5; python_version < '3'",
  "importlib-resources; python_version < '3.7'",
]
