
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T11:38:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0136897b3b3f599dd89b11f41c0ff1b081b0c16",
 "version": "0.7.1.post.dev84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
