
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-11T15:17:03+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3596f63fc5d87a061caa66a5baa7bae5c1ef8ff",
 "version": "1.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
