
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-11T12:37:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "400dbbf3a62ca0e9933b8a457eb2912541920c58",
 "version": "v0.12.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
