[tool.poetry]
name = "atrends"
version = "0.1.1"
description = "A PyTrends script to access the Google Trends API and return a plot."
authors = ["davidshivaji <davidshivaji@gmail.com>"]
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
trends = "atrends.main:start"
atrends = "atrends.main:start"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.4.3"
pytrends = "^4.7.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
