[tool.poetry]
name = "lesspass-client"
version = "0.1.0"
description = "A LessPass API client written in Python"
authors = ["Kyle Williams <kyle.anthony.williams2@gmail.com>"]
license = "Unlicense"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.26.0"
lesspass = "^10.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
lesspass-client = "lesspass_client.cli:main"
