
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T16:33:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb33d0cd8c61d960cd7e5070d8b56d1a8805edae",
 "version": "0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
