name: starry
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl-service>=2.3.0
  - numpy>=1.19.2
  - openblas>=0.3.6
  - pip>=20.3.3
  - python>=3.7.3
  - scipy>=1.5.0
  - setuptools>=51.3.3
  - ffmpeg>=4.2.2
  - nb_conda>=2.2.1
  - nb_conda_kernels>=2.3.0
  - ipywidgets>=7.5.1
