
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-11T23:28:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "63972ca1d998a5ece20d0911111c48f5a9b21e22",
 "version": "0.30.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
