--<ScriptOptions statementTerminator=";"/>

--CONNECT TO BLUDB;


GRANT select on table SYSCAT.COLAUTH                            to GROUP BLUADMIN;
GRANT select on table SYSCAT.COLAUTH                            to GROUP BLUUSERS;

GRANT select on table SYSCAT.CONTROLS                           to GROUP BLUADMIN;
GRANT select on table SYSCAT.CONTROLS                           to GROUP BLUUSERS;

GRANT select on table SYSCAT.DBAUTH                             to GROUP BLUADMIN;
GRANT select on table SYSCAT.DBAUTH                             to GROUP BLUUSERS;

GRANT select on table SYSCAT.INDEXAUTH                          to GROUP BLUADMIN;
GRANT select on table SYSCAT.INDEXAUTH                          to GROUP BLUUSERS;

GRANT select on table SYSCAT.LIBRARYAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.LIBRARYAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.MODULEAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSCAT.MODULEAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSCAT.PACKAGEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.PACKAGEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.PASSTHRUAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.PASSTHRUAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.ROLEAUTH                           to GROUP BLUADMIN;
GRANT select on table SYSCAT.ROLEAUTH                           to GROUP BLUUSERS;

GRANT select on table SYSCAT.ROUTINEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.ROUTINEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.SCHEMAAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSCAT.SCHEMAAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELACCESS                to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELACCESS                to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELCOMPONENTELEMENTS     to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELCOMPONENTELEMENTS     to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELCOMPONENTS            to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELCOMPONENTS            to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELS                     to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELS                     to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYPOLICIES                   to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYPOLICIES                   to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYPOLICYCOMPONENTRULES       to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYPOLICYCOMPONENTRULES       to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYPOLICYEXEMPTIONS           to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYPOLICYEXEMPTIONS           to GROUP BLUUSERS;

GRANT select on table SYSCAT.SEQUENCEAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.SEQUENCEAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.SURROGATEAUTHIDS                   to GROUP BLUADMIN;
GRANT select on table SYSCAT.SURROGATEAUTHIDS                   to GROUP BLUUSERS;

GRANT select on table SYSCAT.TABAUTH                            to GROUP BLUADMIN;
GRANT select on table SYSCAT.TABAUTH                            to GROUP BLUUSERS;

GRANT select on table SYSCAT.TBSPACEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.TBSPACEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.VARIABLEAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.VARIABLEAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.WORKLOADAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.WORKLOADAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.XSROBJECTAUTH                      to GROUP BLUADMIN;
GRANT select on table SYSCAT.XSROBJECTAUTH                      to GROUP BLUUSERS;

GRANT select on table SYSIBMADM.AUTHORIZATIONIDS                to GROUP BLUADMIN;
GRANT select on table SYSIBMADM.AUTHORIZATIONIDS                to GROUP BLUUSERS;

GRANT select on table SYSIBMADM.OBJECTOWNERS                    to GROUP BLUADMIN;
GRANT select on table SYSIBMADM.OBJECTOWNERS                    to GROUP BLUUSERS;

GRANT select on table SYSIBMADM.PRIVILEGES                      to GROUP BLUADMIN;
GRANT select on table SYSIBMADM.PRIVILEGES                      to GROUP BLUUSERS;

GRANT select on table SYSIBM.SQLCOLPRIVILEGES                   to GROUP BLUADMIN;
GRANT select on table SYSIBM.SQLCOLPRIVILEGES                   to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSXSROBJECTAUTH                   to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSXSROBJECTAUTH                   to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSWORKLOADAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSWORKLOADAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSVARIABLEAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSVARIABLEAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSUSERAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSUSERAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSTBSPACEAUTH                     to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSTBSPACEAUTH                     to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSTABAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSTABAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSURROGATEAUTHIDS                to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSURROGATEAUTHIDS                to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSEQUENCEAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSEQUENCEAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYPOLICYEXEMPTIONS        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYPOLICYEXEMPTIONS        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYPOLICYCOMPONENTRULES    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYPOLICYCOMPONENTRULES    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYPOLICIES                to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYPOLICIES                to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELS                  to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELS                  to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTS         to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTS         to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTELEMENTS  to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTELEMENTS  to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELACCESS             to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELACCESS             to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSCHEMAAUTH                      to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSCHEMAAUTH                      to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSROUTINEAUTH                     to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSROUTINEAUTH                     to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSROLEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSROLEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSPLANAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSPLANAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSPASSTHRUAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSPASSTHRUAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSMODULEAUTH                      to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSMODULEAUTH                      to GROUP BLUUSERS;

GRANT select on table SYSCAT.COLAUTH                            to GROUP BLUADMIN;
GRANT select on table SYSCAT.COLAUTH                            to GROUP BLUUSERS;

GRANT select on table SYSCAT.CONTROLS                           to GROUP BLUADMIN;
GRANT select on table SYSCAT.CONTROLS                           to GROUP BLUUSERS;

GRANT select on table SYSCAT.DBAUTH                             to GROUP BLUADMIN;
GRANT select on table SYSCAT.DBAUTH                             to GROUP BLUUSERS;

GRANT select on table SYSCAT.INDEXAUTH                          to GROUP BLUADMIN;
GRANT select on table SYSCAT.INDEXAUTH                          to GROUP BLUUSERS;

GRANT select on table SYSCAT.LIBRARYAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.LIBRARYAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.MODULEAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSCAT.MODULEAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSCAT.PACKAGEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.PACKAGEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.PASSTHRUAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.PASSTHRUAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.ROLEAUTH                           to GROUP BLUADMIN;
GRANT select on table SYSCAT.ROLEAUTH                           to GROUP BLUUSERS;

GRANT select on table SYSCAT.ROUTINEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.ROUTINEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.SCHEMAAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSCAT.SCHEMAAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELACCESS                to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELACCESS                to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELCOMPONENTELEMENTS     to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELCOMPONENTELEMENTS     to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELCOMPONENTS            to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELCOMPONENTS            to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYLABELS                     to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYLABELS                     to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYPOLICIES                   to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYPOLICIES                   to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYPOLICYCOMPONENTRULES       to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYPOLICYCOMPONENTRULES       to GROUP BLUUSERS;

GRANT select on table SYSCAT.SECURITYPOLICYEXEMPTIONS           to GROUP BLUADMIN;
GRANT select on table SYSCAT.SECURITYPOLICYEXEMPTIONS           to GROUP BLUUSERS;

GRANT select on table SYSCAT.SEQUENCEAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.SEQUENCEAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.SURROGATEAUTHIDS                   to GROUP BLUADMIN;
GRANT select on table SYSCAT.SURROGATEAUTHIDS                   to GROUP BLUUSERS;

GRANT select on table SYSCAT.TABAUTH                            to GROUP BLUADMIN;
GRANT select on table SYSCAT.TABAUTH                            to GROUP BLUUSERS;

GRANT select on table SYSCAT.TBSPACEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSCAT.TBSPACEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSCAT.VARIABLEAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.VARIABLEAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.WORKLOADAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSCAT.WORKLOADAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSCAT.XSROBJECTAUTH                      to GROUP BLUADMIN;
GRANT select on table SYSCAT.XSROBJECTAUTH                      to GROUP BLUUSERS;

GRANT select on table SYSIBMADM.AUTHORIZATIONIDS                to GROUP BLUADMIN;
GRANT select on table SYSIBMADM.AUTHORIZATIONIDS                to GROUP BLUUSERS;

GRANT select on table SYSIBMADM.OBJECTOWNERS                    to GROUP BLUADMIN;
GRANT select on table SYSIBMADM.OBJECTOWNERS                    to GROUP BLUUSERS;

GRANT select on table SYSIBMADM.PRIVILEGES                      to GROUP BLUADMIN;
GRANT select on table SYSIBMADM.PRIVILEGES                      to GROUP BLUUSERS;

GRANT select on table SYSIBM.SQLCOLPRIVILEGES                   to GROUP BLUADMIN;
GRANT select on table SYSIBM.SQLCOLPRIVILEGES                   to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSXSROBJECTAUTH                   to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSXSROBJECTAUTH                   to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSWORKLOADAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSWORKLOADAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSVARIABLEAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSVARIABLEAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSUSERAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSUSERAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSTBSPACEAUTH                     to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSTBSPACEAUTH                     to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSTABAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSTABAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSURROGATEAUTHIDS                to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSURROGATEAUTHIDS                to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSEQUENCEAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSEQUENCEAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYPOLICYEXEMPTIONS        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYPOLICYEXEMPTIONS        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYPOLICYCOMPONENTRULES    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYPOLICYCOMPONENTRULES    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYPOLICIES                to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYPOLICIES                to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELS                  to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELS                  to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTS         to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTS         to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTELEMENTS  to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELCOMPONENTELEMENTS  to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSECURITYLABELACCESS             to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSECURITYLABELACCESS             to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSSCHEMAAUTH                      to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSSCHEMAAUTH                      to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSROUTINEAUTH                     to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSROUTINEAUTH                     to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSROLEAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSROLEAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSPLANAUTH                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSPLANAUTH                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSPASSTHRUAUTH                    to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSPASSTHRUAUTH                    to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSMODULEAUTH                      to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSMODULEAUTH                      to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSLIBRARYAUTH                     to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSLIBRARYAUTH                     to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSINDEXAUTH                       to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSINDEXAUTH                       to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSDBAUTH                          to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSDBAUTH                          to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSCONTROLS                        to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSCONTROLS                        to GROUP BLUUSERS;

GRANT select on table SYSIBM.SYSCOLAUTH                         to GROUP BLUADMIN;
GRANT select on table SYSIBM.SYSCOLAUTH                         to GROUP BLUUSERS;

GRANT select on table SYSIBM.SQLTABLEPRIVILEGES                 to GROUP BLUADMIN;
GRANT select on table SYSIBM.SQLTABLEPRIVILEGES                 to GROUP BLUUSERS;


GRANT SELECT ON SYSCAT.AUDITPOLICIES TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.AUDITPOLICIES TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSAUDITPOLICIES TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSAUDITPOLICIES TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.AUDITUSE TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.AUDITUSE TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSAUDITUSE TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSAUDITUSE TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.EVENTS TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.EVENTS TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSEVENTS TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSEVENTS TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.EVENTTABLES TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.EVENTTABLES TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSEVENTTABLES TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSEVENTTABLES TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.PACKAGES TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.PACKAGES TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSPLAN TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSPLAN TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.PROCEDURES TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.PROCEDURES TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.ROLES TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.ROLES TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSROLES TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSROLES TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.ROUTINES TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.ROUTINES TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSROUTINES TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSROUTINES TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.SCHEMATA TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.SCHEMATA TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSSCHEMATA TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSSCHEMATA TO GROUP BLUUSERS;

GRANT SELECT ON SYSCAT.STATEMENTS TO GROUP BLUADMIN;
GRANT SELECT ON SYSCAT.STATEMENTS TO GROUP BLUUSERS;

GRANT SELECT ON SYSIBM.SYSSTMT TO GROUP BLUADMIN;
GRANT SELECT ON SYSIBM.SYSSTMT TO GROUP BLUUSERS;


GRANT SELECT ON SYSSTAT.COLDIST TO GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.COLDIST TO GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.COLGROUPDIST TO GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.COLGROUPDIST TO GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.COLGROUPDISTCOUNTS TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.COLGROUPDISTCOUNTS TO  GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.COLGROUPS TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.COLGROUPS TO  GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.COLUMNS TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.COLUMNS TO  GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.FUNCTIONS TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.FUNCTIONS TO  GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.INDEXES TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.INDEXES TO  GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.ROUTINES TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.ROUTINES TO  GROUP BLUUSERS;

GRANT SELECT ON SYSSTAT.TABLES TO  GROUP BLUADMIN;
GRANT SELECT ON SYSSTAT.TABLES TO  GROUP BLUUSERS;


GRANT CREATE_EXTERNAL_ROUTINE ON DATABASE TO GROUP BLUUSERS;
GRANT EXECUTE ON FUNCTION SYSPROC.MON_GET_INSTANCE TO USER BLUADMIN_MON;

GRANT EXECUTE ON PROCEDURE "CONNECT_CHECK" to PUBLIC;     
       
UPDATE DB CFG FOR BLUDB USING CONNECT_PROC NULL IMMEDIATE;
UPDATE DB CFG FOR BLUDB USING  CONNECT_PROC "DB2INST1.CONNECT_CHECK";

--CONNECT RESET;
--TERMINATE;
