[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "yade"
authors = [{name = "djbios", email = "dorandval@gmail.com"}]
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
readme = "README.MD"
keywords = ['django', 'environment', 'settings']

[project.urls]
Home = "https://github.com/djbios/yade"
