[tool.poetry]
name = "verbcl-elastic"
version = "0.4.0"
description = "VerbCL Elastic"
authors = ["Julien Rossi <j.rossi@uva.nl>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/j-rossi-nl/verbcl-elastic"
repository = "https://github.com/j-rossi-nl/verbcl-elastic"
documentation = "https://verbcl-elastic.readthedocs.io"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://github.com/j-rossi-nl/verbcl-elastic/releases"

[tool.poetry.dependencies]
python = "^3.6.1"
click = "^8.0.1"
elasticsearch = "^7.15.0"
elasticsearch-dsl = "^7.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = {extras = ["toml"], version = "^6.0"}
safety = "^1.10.3"
mypy = "^0.910"
typeguard = "^2.13.0"
xdoctest = {extras = ["colors"], version = "^0.15.5"}
sphinx = "^4.2.0"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^2.15.0"
flake8 = "^3.9.2"
black = "^20.8b1"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.9.2"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.0"
reorder-python-imports = "^2.6.0"
pre-commit-hooks = "^4.0.1"
sphinx-rtd-theme = "^1.0.0"
sphinx-click = "^3.0.1"
Pygments = "^2.10.0"
nox-poetry = "^0.8.6"

[tool.poetry.scripts]
verbcl-elastic = "verbcl_elastic.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["verbcl_elastic"]

[tool.coverage.report]
show_missing = true
fail_under = 50

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = "elasticsearch_dsl.*"
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
