
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-13T10:30:27+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b56135eff6e4ac1d1f3a10e0eba93366fe728136",
 "version": "1.85"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
