
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-18T19:42:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0b1bf0ea53ce4e566d7e7ba0198713edf5b8dbe",
 "version": "2021.10.18dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
