[tool.coverage.paths]
source=["src","*/site-packages"]

[tool.coverage.run]
branch=true
source=["jira_commonmark"]

[tool.coverage.report]
show_missing=true

[tool.poetry]
name = 'dakan-eda'
version = '0.0.12'
description = "EDA data for dakan"
authors = ["vrekkebo <vebjorn.rekkebo@nav.no>"]
readme = "README.md"
homepage = "https://github.com/navikt/dakan-eda"
repository = "https://github.com/navikt/dakan-eda"
keywords = ["dakan", "eda"]

[tool.poetry.dependencies]
python = "^3.7,<3.10"
google-cloud-bigquery = "^2.26.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"