# Generated by Django 3.1.7 on 2021-04-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_reaktion_crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Namn')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Skapad')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='clients',
            name='bot',
            field=models.IntegerField(default=0, verbose_name='Bot'),
        ),
        migrations.CreateModel(
            name='NewsletterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Link')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_link_for_newsletter', to='django_reaktion_crm.newsletter')),
            ],
        ),
    ]
