# Generated by Django 3.1.8 on 2021-10-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reaktion_crm', '0002_auto_20210412_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='campaigns',
            field=models.ManyToManyField(to='django_reaktion_crm.Newsletter'),
        ),
    ]
