# Generated by Django 3.2.8 on 2021-10-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_reaktion_crm', '0003_clients_campaigns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Kampanj', 'verbose_name_plural': 'Kampanjer'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='campaigns',
            field=models.ManyToManyField(to='django_reaktion_crm.Newsletter', verbose_name='kampanjer'),
        ),
    ]
