from typing import Any

from google.auth import (
    environment_vars as environment_vars,
    exceptions as exceptions,
    jwt as jwt,
)
from google.auth.transport import requests as requests

async def verify_token(
    id_token, request, audience: Any | None = ..., certs_url=...
): ...
async def verify_oauth2_token(id_token, request, audience: Any | None = ...): ...
async def verify_firebase_token(id_token, request, audience: Any | None = ...): ...
async def fetch_id_token(request, audience): ...
