from typing import Any

from google.auth import (
    environment_vars as environment_vars,
    exceptions as exceptions,
    jwt as jwt,
)

def verify_token(id_token, request, audience: Any | None = ..., certs_url=...): ...
def verify_oauth2_token(id_token, request, audience: Any | None = ...): ...
def verify_firebase_token(id_token, request, audience: Any | None = ...): ...
def fetch_id_token(request, audience): ...
