[tool.poetry]
name = "wakeonlan"
version = "2.1.0"
description = "A small python module for wake on lan."
authors = ["Remco Haszing <remcohaszing@gmail.com>"]
license = "MIT"
readme = "README.rst"
documentation = "http://pywakeonlan.readthedocs.io"
repository = "https://github.com/remcohaszing/pywakeonlan"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Topic :: System :: Networking"
]

[tool.poetry.scripts]
wakeonlan = "wakeonlan:main"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.9.0"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.1"
pytest = "^6.2.3"
pytest-cov = "^2.11.1"
sphinx = "^3.5.3"
sphinx-rtd-theme = "^0.5.1"
mypy = "^0.812"

[tool.coverage.run]
branch = true
source = ["wakeonlan"]

[tool.coverage.report]
show_missing = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
