[tool.poetry]
name = "djs3"
version = "2021.10.11"
description = "S3 in Django"
authors = ["Atem18 <messer.kevin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.18.59"
Django = "^3.2.8"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
