
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-15T17:12:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "47248f7b67d841631a4ac9290279aca16fec850a",
 "version": "0.1.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
