[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "wheel",
    "milksnake>=0.1.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "cmsis_pack_manager/_version.py"
