info = {"message": "[docs] Add docsearch integration (#1596)", "commit": "25ba33db7c819dcc47aa60aa3dea98f8da699ee6", "date": "2021-10-15 21:56:34 +0300", "branch": "master", "version": "1.3.0+84.g25ba33db.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
