[tool.poetry]
name = "anchorpy"
version = "0.1.0"
description = ""
authors = ["kevinheavey <kevinheavey123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
construct-typing = "^0.5.1"
solana = "^0.16.0"
sumtypes = "^0.1a5"
apischema = "^0.15.6"
borsh-construct-tmp = "^0.1.0"
inflection = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
wemake-python-styleguide = "^0.15.3"
mypy = "^0.910"
black = "^21.7b0"
pydocstyle = "^6.1.1"
isort = "^5.9.3"
pytest-asyncio = "^0.15.1"
mkdocs-material = "^7.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
