[tool.poetry]
name = "qtl_metrics"
version = "1.0.1"
description = "Quantalon Metrics"
authors = ["Quantalon <dev@quantalon.com>"]
readme = "README.md"
license = "MIT"
keywords = ['quant']

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
